# Config used by cryptogen
OrdererOrgs:
    - Name: Orderer
      Domain: care.com
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: Org1
      Domain: org1.care.com
      EnableNodeOUs: true
      Template:
        Count: 1 # number instances
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org2
      Domain: org2.care.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 2
    - Name: Org3
      Domain: org3.care.com
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 2
    - Name: Org4
      Domain: org4.care.com
      EnableNodeOUs: true    
      Template:
        Count: 2
        SANS:
          - localhost
      Users:
        Count: 3
  
